print("===============================================")
print("Nombre: Daniel Martinez Zepeta                 ")
print("===============================================")
print("Domicilio: Ignacio Allende, Huixquilucan       ")
print("===============================================")
print("Color Fav: Aqua                                ")
print("===============================================")
print("Hobbies: Jugar videojuegos                     ")
print("===============================================")