print("===============================================")
print("Nombre: Dylan yael hernandez martinez                 ")
print("===============================================")
print("vivo en : san francisco chimalpa,naucalpan   ")
print("===============================================")
print("Color Fav:azul, negro y lila                         ")
print("===============================================")
print("hobbies: salir a pasear, hacer deporte, leer, dormir y trabajar")
print("===============================================")