print("===============================================")
print("Nombre: Juan Carlos Alvares Ortiz              ")
print("===============================================")
print("Domicilio: la lumbrera, Huixquilucan           ")
print("===============================================")
print("Color Fav: negro                               ")
print("===============================================")
print("Hobbies: comer, escuchar musica y dormir       ")
print("===============================================")